const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const React=require('react'),Renderer=require('react-test-renderer'),ts=require('typescript');
global.IS_REACT_ACT_ENVIRONMENT=true;
const {act}=Renderer;
const routes=[],calls=[];
const profile={id:'test-user',nickname:'Medi',pet_name:'Miko',opening_balance:1000000,onboarding_complete:true,reduce_motion:true};
const ledger={profile,transactions:[],goals:[],contributions:[],checkins:[],accessories:[],loading:false,error:'',refresh:async()=>{}};
const api={auth:{getSession:async()=>({data:{session:{user:{id:'test-user',email:'tester@example.com'}}}}),onAuthStateChange:()=>({data:{listener:{},subscription:{unsubscribe(){}}}}),signUp:async args=>{calls.push(['signup',args]);return{data:{session:null},error:null}},verifyOtp:async args=>{calls.push(['verify',args]);return{data:{},error:null}},resend:async()=>({error:null}),resetPasswordForEmail:async()=>({error:null})}};
const hosts={};for(const name of ['ActivityIndicator','Image','KeyboardAvoidingView','Pressable','RefreshControl','ScrollView','Switch','Text','TextInput','View'])hosts[name]=name;
const rn={...hosts,StyleSheet:{create:v=>v},Platform:{OS:'android'},Alert:{alert(){}}};
const cache={};
function load(file){file=path.resolve(__dirname,file);if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;
const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{fileName:file,compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const customRequire=name=>{if(/\.(png|ttf)$/.test(name))return 1;if(name==='react-native')return rn;if(name==='react-native-safe-area-context')return{SafeAreaProvider:'SafeAreaProvider',useSafeAreaInsets:()=>({top:24,bottom:24})};if(name==='expo-router')return{router:{navigate:href=>routes.push(href),replace:href=>routes.push(href)}};if(name==='expo-status-bar')return{StatusBar:'StatusBar'};if(name==='expo-linking')return{getInitialURL:async()=>null,addEventListener:()=>({remove(){}}),parse:()=>({}),openURL:async()=>{}};if(name==='expo-image-picker')return{};if(name==='expo-font')return{useFonts:()=>[true,null]};if(name==='@expo/vector-icons/Ionicons')return 'Icon';if(name==='react-native-reanimated')return{__esModule:true,default:{View:'AnimatedView'},cancelAnimation(){},Easing:{inOut:n=>n,ease:0},useReducedMotion:()=>true,useSharedValue:n=>React.useMemo(()=>({get:()=>n,set(){}}),[]),useAnimatedStyle:fn=>fn(),withTiming:n=>n,withRepeat:n=>n};if(name.endsWith('/lib/supabase')||name==='../lib/supabase')return{supabase:api,AUTH_REDIRECT:'maucuan://auth/callback'};if(name==='./hooks/useLedger')return{useLedger:()=>ledger};if(name.startsWith('.')){let resolved=path.resolve(path.dirname(file),name);if(fs.existsSync(resolved+'.tsx'))return load(path.relative(__dirname,resolved+'.tsx'));if(fs.existsSync(resolved+'.ts'))return require(resolved+'.ts')}return require(name)};
vm.runInThisContext('(function(require,module,exports){'+code+'\n})',{filename:file})(customRequire,module,module.exports);return module.exports}
const Main=load('../src/Main.tsx'),Auth=load('../src/components/Auth.tsx').Auth,UI=load('../src/components/ui.tsx');
const press=(r,label)=>r.root.findAllByType('Pressable').find(n=>n.props.accessibilityLabel===label);
const texts=r=>r.root.findAllByType('Text').map(n=>n.children.filter(x=>typeof x==='string').join('')).join('\n');
function screen(name){return React.createElement(Main.MauCuanProvider,null,React.createElement(Main.MauCuanScreen,{screen:name}))}
test('home actions open distinct screens; route views render forms rather than repeating home',async()=>{let r;await act(async()=>{r=Renderer.create(screen('home'))});for(const [label,destination] of [['Pengaturan','/settings'],['Lihat rincian saldo tercatat','/balance'],['Buka habitat Miko','/pet'],['Scan struk','/scan'],['Catat manual','/entry']]){await act(async()=>press(r,label).props.onPress());assert.equal(routes.at(-1),destination)}for(const [name,title] of [['settings','Profil & pengaturan'],['balance','Rincian saldo'],['scan','Scan struk'],['entry','Catat transaksi'],['pet','Miko si Macan']]){await act(async()=>r.update(screen(name)));assert(texts(r).includes(title),name);assert(!texts(r).includes('Hai, Medi'),name)}await act(async()=>r.unmount())});
test('rupiah field formats without putting separators in saved state',async()=>{let raw='1250000',r;await act(async()=>{r=Renderer.create(React.createElement(UI.Field,{label:'Saldo awal',currency:true,value:raw,onChangeText:v=>raw=v}))});const input=r.root.findByType('TextInput');assert.equal(input.props.value,'1.250.000');assert(texts(r).includes('Rp'));input.props.onChangeText('1.250.0000');assert.equal(raw,'12500000');await act(async()=>r.unmount())});
test('signup presents a code field and verifies the supplied code through Supabase',async()=>{let r;await act(async()=>{r=Renderer.create(React.createElement(Auth,{onError:()=>{}}))});let action=r.root.findAllByType('Pressable').find(n=>texts({root:n}).includes('Buat akun MauCuan'));await act(async()=>action.props.onPress());await act(async()=>{r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='EMAIL').props.onChangeText('tester@example.com');r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='KATA SANDI').props.onChangeText('Test-password-123')});action=r.root.findAllByType('Pressable').find(n=>texts({root:n})==='Buat akun');await act(async()=>action.props.onPress());assert(texts(r).includes('Masukkan kode email'));assert(!texts(r).includes('Buka link'));await act(async()=>r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='Kode verifikasi').props.onChangeText('123456'));action=r.root.findAllByType('Pressable').find(n=>texts({root:n})==='Verifikasi kode');await act(async()=>action.props.onPress());assert.deepEqual(calls.at(-1),['verify',{email:'tester@example.com',token:'123456',type:'email'}]);await act(async()=>r.unmount())});
test('manual entry saves whole rupiah and preserves the draft after backend failure',async()=>{let r,payload,fail=true;api.from=table=>{assert.equal(table,'transactions');return{insert:data=>{payload=data;return{select:()=>({single:async()=>fail?{data:null,error:{message:'Connection unavailable'}}:{data:{id:'saved',...data},error:null}})}}}};await act(async()=>{r=Renderer.create(screen('entry'))});const field=label=>r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel===label);const save=()=>r.root.findAllByType('Pressable').find(n=>texts({root:n})==='Simpan transaksi');await act(async()=>{field('UNTUK APA?').props.onChangeText('Lunch');field('Nominal, rupiah').props.onChangeText('48.000')});await act(async()=>save().props.onPress());assert.equal(payload.amount,48000);assert.equal(payload.user_id,'test-user');assert.equal(field('Nominal, rupiah').props.value,'48.000');assert(texts(r).includes('Connection unavailable'));fail=false;await act(async()=>save().props.onPress());assert.equal(routes.at(-1),'/saved');await act(async()=>r.unmount());delete api.from});
