const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const React=require('react'),Renderer=require('react-test-renderer'),ts=require('typescript');
global.IS_REACT_ACT_ENVIRONMENT=true;
const {act}=Renderer;
const routes=[],calls=[];
const pickerMock={launchImageLibraryAsync:async()=>({canceled:false,assets:[{uri:'file:///data/cache/receipt%20photo.jpg',base64:'dGVzdA==',mimeType:'image/jpeg'}]})};
const ocrMock={isSupported:true,extractReceiptLayout:async path=>{calls.push(['ocrPath',path]);return {width:600,height:800,fragments:['KOPI SENJA','Jl. Merdeka 15','06/10/2026','2 x LATTE 48.000','TOTAL Rp 48.000'].map((text,i)=>({text,x:20,y:20+i*40,width:500,height:20}))}}};
const profile={id:'test-user',nickname:'Medi',pet_name:'Miko',opening_balance:1000000,onboarding_complete:true,reduce_motion:true};
const ledger={profile,transactions:[],goals:[],contributions:[],checkins:[],accessories:[],loading:false,error:'',refresh:async()=>{}};
const api={auth:{getSession:async()=>({data:{session:{user:{id:'test-user',email:'tester@example.com'}}}}),onAuthStateChange:()=>({data:{listener:{},subscription:{unsubscribe(){}}}}),signUp:async args=>{calls.push(['signup',args]);return{data:{session:null},error:null}},verifyOtp:async args=>{calls.push(['verify',args]);return{data:{},error:null}},resend:async()=>({error:null}),resetPasswordForEmail:async()=>({error:null})}};
let storedQuiz;
test.beforeEach(()=>{storedQuiz=undefined;});
api.rpc=async(name,args={})=>{assert.equal(name,'daily_quiz'); if(!storedQuiz)storedQuiz={day:'2026-10-06',question_ids:['q001','q002','q003','q004','q005'],answers:[],completed:false,reward:0}; if(args.p_question && storedQuiz.question_ids.indexOf(args.p_question)===storedQuiz.answers.length){storedQuiz.answers.push(args.p_answer);storedQuiz.completed=storedQuiz.answers.length===5;storedQuiz.reward=storedQuiz.completed?5:0;} return{data:structuredClone(storedQuiz),error:null};};
const hosts={};for(const name of ['Modal','ActivityIndicator','Image','KeyboardAvoidingView','Pressable','RefreshControl','ScrollView','Switch','Text','TextInput','View'])hosts[name]=name;
const rn={...hosts,StyleSheet:{create:v=>v},Platform:{OS:'android'},Alert:{alert(){}},useWindowDimensions:()=>({width:400,height:800})};
const cache={};
function load(file){file=path.resolve(__dirname,file);if(cache[file])return cache[file].exports;const module={exports:{}};cache[file]=module;
const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{fileName:file,compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
const customRequire=name=>{if(name.endsWith('/hooks/useDailyQuiz'))return load('../src/hooks/useDailyQuiz.ts');if(name==='@expo/ui')return{Host:'Host',Row:'SheetRow',Column:'SheetColumn',Text:'SheetText',Button:'SheetButton',BottomSheet:props=>props.isPresented?React.createElement('BottomSheet',props,props.children):null};if(name.endsWith('/hooks/usePetWidget'))return{usePetWidget(){},requestPetWidget:()=>false};if(name.endsWith('/hooks/usePetReminders'))return{usePetReminders:()=>({state:{enabled:false,automatic:true,hour:20,activity:[]},error:'',toggle:async()=>{},setHour(){},setAutomatic(){},record:async()=>{}})};if(name==='@expo/ui/community/datetime-picker')return{DateTimePicker:'DateTimePicker'};if(name==='react-native-svg')return{__esModule:true,default:'Svg',Circle:'Circle',Ellipse:'Ellipse',G:'G',Path:'Path',Rect:'Rect',Line:'Line'};if(name==='react-native-worklets')return{scheduleOnRN:(fn,...args)=>fn(...args)};if(name==='react-native-gesture-handler'){const pan={hooks:{},activateAfterLongPress(ms){this.delay=ms;return this},onStart(fn){this.hooks.start=fn;return this},onUpdate(fn){this.hooks.update=fn;return this},onFinalize(fn){this.hooks.finalize=fn;return this}};return{Gesture:{Pan:()=>pan,Tap:()=>({maxDuration(){return this},onEnd(fn){this.end=fn;return this}}),Exclusive:(...gestures)=>({gestures})},GestureDetector:'GestureDetector',GestureHandlerRootView:'GestureHandlerRootView'}};if(/\.(png|ttf)$/.test(name))return 1;if(name==='react-native')return rn;if(name==='react-native-safe-area-context')return{SafeAreaProvider:'SafeAreaProvider',useSafeAreaInsets:()=>({top:24,bottom:24})};if(name==='expo-router')return{router:{navigate:href=>routes.push(href),replace:href=>routes.push(href)}};if(name==='expo-status-bar')return{StatusBar:'StatusBar'};if(name==='expo-linking')return{getInitialURL:async()=>null,addEventListener:()=>({remove(){}}),parse:()=>({}),openURL:async()=>{}};if(name==='expo-image-picker')return pickerMock;if(name==='expo-text-extractor')return ocrMock;if(name==='expo-font')return{useFonts:()=>[true,null]};if(name==='@expo/vector-icons/Ionicons')return 'Icon';if(name==='react-native-reanimated')return{__esModule:true,default:{View:'AnimatedView'},cancelAnimation(){},Easing:{inOut:n=>n,ease:0},useReducedMotion:()=>true,useSharedValue:n=>React.useMemo(()=>({value:n,get(){return this.value},set(v){this.value=v}}),[]),useAnimatedStyle:fn=>fn(),withTiming:n=>n,withRepeat:n=>n,withSequence:(...n)=>n.at(-1)};if(name.endsWith('/lib/supabase')||name==='../lib/supabase')return{supabase:api,AUTH_REDIRECT:'maucuan://auth/callback'};if(name==='./hooks/useLedger')return{useLedger:()=>ledger};if(name.startsWith('.')){let resolved=path.resolve(path.dirname(file),name);if(fs.existsSync(resolved)&&resolved.endsWith('.ts'))return require(resolved);if(fs.existsSync(resolved+'.tsx'))return load(path.relative(__dirname,resolved+'.tsx'));if(fs.existsSync(resolved+'.ts'))return require(resolved+'.ts')}return require(name)};
vm.runInThisContext('(function(require,module,exports){'+code+'\n})',{filename:file})(customRequire,module,module.exports);return module.exports}
const Main=load('../src/Main.tsx'),Auth=load('../src/components/Auth.tsx').Auth,UI=load('../src/components/ui.tsx');
const Dates=load('../src/components/date-field.tsx'),Pets=load('../src/components/pet-habitat.tsx');
const press=(r,label)=>r.root.findAllByType('Pressable').find(n=>n.props.accessibilityLabel===label);
const texts=r=>r.root.findAll(n=>n.type==='Text'||n.type==='SheetText').map(n=>n.children.filter(x=>typeof x==='string').join('')).join('\n');
function screen(name){return React.createElement(Main.MauCuanProvider,null,React.createElement(Main.MauCuanScreen,{screen:name}))}
test('home actions open distinct screens; route views render forms rather than repeating home',async()=>{let r;await act(async()=>{r=Renderer.create(screen('home'))});for(const [label,destination] of [['Pengaturan','/settings'],['Lihat rincian saldo tercatat','/balance'],['Buka habitat Miko','/pet'],['Scan struk','/scan'],['Catat manual','/entry']]){await act(async()=>press(r,label).props.onPress());assert.equal(routes.at(-1),destination)}for(const [name,title] of [['settings','Profil & pengaturan'],['balance','Rincian saldo'],['scan','Scan struk'],['entry','Catat transaksi'],['pet','Miko si Macan']]){await act(async()=>r.update(screen(name)));assert(texts(r).includes(title),name);assert(!texts(r).includes('Hai, Medi'),name)}await act(async()=>r.unmount())});
test('rupiah field formats without putting separators in saved state',async()=>{let raw='1250000',r;await act(async()=>{r=Renderer.create(React.createElement(UI.Field,{label:'Saldo awal',currency:true,value:raw,onChangeText:v=>raw=v}))});const input=r.root.findByType('TextInput');assert.equal(input.props.value,'1.250.000');assert(texts(r).includes('Rp'));input.props.onChangeText('1.250.0000');assert.equal(raw,'12500000');await act(async()=>r.unmount())});
test('signup presents a code field and verifies the supplied code through Supabase',async()=>{let r;await act(async()=>{r=Renderer.create(React.createElement(Auth,{onError:()=>{}}))});let action=r.root.findAllByType('Pressable').find(n=>texts({root:n}).includes('Buat akun MauCuan'));await act(async()=>action.props.onPress());await act(async()=>{r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='EMAIL').props.onChangeText('tester@example.com');r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='KATA SANDI').props.onChangeText('Test-password-123')});action=r.root.findAllByType('Pressable').find(n=>texts({root:n})==='Buat akun');await act(async()=>action.props.onPress());assert(texts(r).includes('Masukkan kode email'));assert(!texts(r).includes('Buka link'));await act(async()=>r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel==='Kode verifikasi').props.onChangeText('123456'));action=r.root.findAllByType('Pressable').find(n=>texts({root:n})==='Verifikasi kode');await act(async()=>action.props.onPress());assert.deepEqual(calls.at(-1),['verify',{email:'tester@example.com',token:'123456',type:'email'}]);await act(async()=>r.unmount())});
test('manual entry saves whole rupiah and preserves the draft after backend failure',async()=>{let r,payload,fail=true;api.from=table=>{assert.equal(table,'transactions');return{insert:data=>{payload=data;return{select:()=>({single:async()=>fail?{data:null,error:{message:'Connection unavailable'}}:{data:{id:'saved',...data},error:null}})}}}};await act(async()=>{r=Renderer.create(screen('entry'))});const field=label=>r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel===label);const save=()=>r.root.findAllByType('Pressable').find(n=>texts({root:n})==='Simpan transaksi');await act(async()=>{field('UNTUK APA?').props.onChangeText('Lunch');field('Nominal, rupiah').props.onChangeText('48.000')});await act(async()=>save().props.onPress());assert.equal(payload.amount,48000);assert.equal(payload.user_id,'test-user');assert.equal(field('Nominal, rupiah').props.value,'48.000');assert(texts(r).includes('Connection unavailable'));fail=false;await act(async()=>save().props.onPress());assert.equal(routes.at(-1),'/saved');await act(async()=>r.unmount());delete api.from});
test('date picker cancels without changing value, confirms a calendar day, and clears target date',async()=>{
 let r,value='2026-10-06';await act(async()=>{r=Renderer.create(React.createElement(Dates.DateField,{label:'Tanggal target',value,onChange:v=>value=v,clearable:true}))});
 assert.equal(r.root.findAllByType('TextInput').length,0);
 await act(async()=>press(r,'Pilih tanggal target').props.onPress());
 await act(async()=>r.root.findByType('DateTimePicker').props.onDismiss());assert.equal(value,'2026-10-06');
 await act(async()=>press(r,'Pilih tanggal target').props.onPress());
 await act(async()=>r.root.findByType('DateTimePicker').props.onValueChange({},new Date('2027-01-12T00:00:00Z')));assert.equal(value,'2027-01-12');assert.equal(r.root.findAllByType('DateTimePicker').length,0);
 await act(async()=>press(r,'Hapus tanggal target').props.onPress());assert.equal(value,'');await act(async()=>r.unmount());
});
test('shop locks level gifts, equips owned items, and removes equipped items',async()=>{
 const actions=[];let r;const props={level:2,leaves:20,accessories:[{accessory:'explorer_hat',cost:80}],room:{},busy:false,redeem:id=>actions.push(['buy',id]),equip:(slot,id)=>actions.push(['equip',slot,id])};
 await act(async()=>{r=Renderer.create(React.createElement(Pets.PetShop,props))});
 const button=text=>r.root.findAll(n=>n.type==='Pressable'||n.type==='SheetButton').find(n=>texts({root:n})===text);
 assert(button('Terbuka di level 5').props.disabled);assert(button('Perlu 60 daun').props.disabled);
 await act(async()=>button('Pasang').props.onPress());assert.deepEqual(actions.at(-1),['equip','head','explorer_hat']);
 await act(async()=>r.update(React.createElement(Pets.PetShop,{...props,room:{head:'explorer_hat'}})));
 await act(async()=>button('Lepas').props.onPress());assert.deepEqual(actions.at(-1),['equip','head',null]);
 await act(async()=>button('Ambil hadiah level').props.onPress());assert.deepEqual(actions.at(-1),['buy','rug_cloud']);await act(async()=>r.unmount());
});
test('scene accessibility actions replace the redundant petting button and quiz can complete',async()=>{
 let r;await act(async()=>{r=Renderer.create(screen('pet'))});const button=text=>r.root.findAll(n=>n.type==='Pressable'||n.type==='SheetButton').find(n=>texts({root:n})===text);
 assert.equal(button('Elus Miko'),undefined); const scene=r.root.findAllByType('AnimatedView').find(n=>n.props.onAccessibilityAction); await act(async()=>scene.props.onAccessibilityAction({nativeEvent:{actionName:'pet'}}));assert(texts(r).includes('Oh… makasih. Pelan-pelan, ya.'));
 await act(async()=>button('Main kuis').props.onPress());
 const {moneyQuiz}=require('../src/lib/pet.ts');for(const q of moneyQuiz){await act(async()=>button(q.answers[q.correct]).props.onPress());assert(texts(r).includes(q.explanation));assert.equal(r.root.findAllByType('BottomSheet').length,0);await act(async()=>press(r,'Lanjut').props.onPress())}
 assert(texts(r).includes('5 dari 5 benar'));await act(async()=>r.unmount());
});
test('long hold and enough strokes trigger Miko happiness; short movement does not',async()=>{
 let r;await act(async()=>{r=Renderer.create(screen('pet'))});
 const gesture=r.root.findByType('GestureDetector').props.gesture.gestures[0];assert.equal(gesture.delay,550);
 await act(async()=>gesture.hooks.start({x:40,y:80}));assert(texts(r).includes('Oh? Mau elus?'));
 await act(async()=>gesture.hooks.update({x:65,y:80}));assert(!texts(r).includes('Hmm, ternyata enak juga.'));
 await act(async()=>gesture.hooks.update({x:230,y:80}));assert(texts(r).includes('Hmm, ternyata enak juga.'));
 assert.equal(r.root.findByType('GestureDetector').props.gesture.gestures[0],gesture,'gesture survives expression changes');
 await act(async()=>gesture.hooks.finalize());await act(async()=>r.unmount());
});
test('gallery scan passes a usable Android path, opens editable rows and saves reviewed items',async()=>{
 let r,payload;api.from=()=>({insert:data=>{payload=data;return{select:()=>({single:async()=>({data:{id:'receipt-saved',...data},error:null})})}}});
 api.storage={from:()=>({upload:async()=>({error:null})})};
 await act(async()=>{r=Renderer.create(screen('scan'))});
 const button=text=>r.root.findAll(n=>n.type==='Pressable'||n.type==='SheetButton').find(n=>texts({root:n})===text);
 await act(async()=>button('Pilih dari galeri').props.onPress());assert.equal(routes.at(-1),'/receipt');assert(calls.some(c=>c[0]==='ocrPath' && c[1]==='/data/cache/receipt photo.jpg'));
 await act(async()=>r.update(screen('receipt')));
 const field=label=>r.root.findAllByType('TextInput').find(n=>n.props.accessibilityLabel===label);
 assert.equal(field('Nama toko').props.value,'KOPI SENJA');assert.equal(field('Nominal, rupiah').props.value,'48.000');assert.equal(field('Barang 1').props.value,'LATTE');
 await act(async()=>field('Barang 1').props.onChangeText('Latte besar'));
 await act(async()=>button('Simpan transaksi').props.onPress());assert.equal(routes.at(-1),'/saved');assert.equal(payload.amount,48000);assert.equal(payload.occurred_on,'2026-10-06');assert.deepEqual(payload.receipt_items,[{name:'Latte besar',quantity:2,amount:48000}]);
 await act(async()=>r.unmount());delete api.from;delete api.storage;
});


test('tap-to-tos, ball play and chat rotate Miko reactions without rewarding transactions',async()=>{
 let r;await act(async()=>{r=Renderer.create(screen('pet'))});const button=text=>r.root.findAll(n=>n.type==='Pressable'||n.type==='SheetButton').find(n=>texts({root:n})===text);
 const tap=r.root.findByType('GestureDetector').props.gesture.gestures[1];await act(async()=>tap.end({},false));assert(!texts(r).includes('Tos!'));
 await act(async()=>tap.end({},true));assert(texts(r).includes('Tos!'));
 await act(async()=>button('Lempar bola').props.onPress());assert(button('Miko mengejar bola…').props.disabled);assert(texts(r).includes('aku siap'));
 await act(async()=>new Promise(resolve=>setTimeout(resolve,1200)));assert(button('Lempar bola'));assert(!texts(r).includes('aku siap'));
 const before=texts(r);await act(async()=>button('Ajak ngobrol').props.onPress());assert.notEqual(texts(r),before);
 assert.equal(button('Elus Miko'),undefined);assert(!texts(r).includes('Level 1 —'));await act(async()=>r.unmount());
});

test('quiz popup dismisses and reopens without losing the question or moving the room',async()=>{let r;await act(async()=>{r=Renderer.create(screen('pet'))});try{const room=()=>r.root.findByProps({testID:'pet-room'});const bubble=()=>r.root.findByProps({testID:'pet-speech'});const height=room().props.style.height;await act(async()=>press(r,'Main kuis').props.onPress());assert.equal(r.root.findAllByType('BottomSheet').length,1);const q=require('../src/lib/pet.ts').moneyQuiz[0];assert(texts({root:bubble()}).includes(q.question));await act(async()=>r.root.findByType('BottomSheet').props.onDismiss());assert.equal(r.root.findAllByType('BottomSheet').length,0);await act(async()=>press(r,'Pilih jawaban').props.onPress());assert.equal(r.root.findAllByType('BottomSheet').length,1);const choice=r.root.findAllByType('SheetButton').find(n=>texts({root:n})===q.answers[q.correct]);await act(async()=>choice.props.onPress());assert.equal(r.root.findAllByType('BottomSheet').length,0);assert(texts({root:bubble()}).includes(q.explanation));assert.equal(room().props.style.height,height);assert(press(r,'Ajak ngobrol').props.disabled);await act(async()=>press(r,'Tutup kuis').props.onPress());assert(!press(r,'Ajak ngobrol').props.disabled);}finally{await act(async()=>r.unmount())}});

test('quiz answers use native controls, select a wrong answer and preserve the decorated interior',async()=>{let r;await act(async()=>{r=Renderer.create(screen('pet'))});try{const room=r.root.findByProps({testID:'pet-room-interior'});assert.equal(room.findAllByProps({testID:'pet-speech'}).length,0,'dialogue cannot cover the decorated viewport');const scene=r.root.findAllByType('AnimatedView').find(n=>n.props.onAccessibilityAction);assert(room.findAll(n=>n===scene).length);const initialHeight=r.root.findByProps({testID:'pet-room'}).props.style.height;await act(async()=>press(r,'Main kuis').props.onPress());const sheet=r.root.findByType('BottomSheet');assert.equal(sheet.findAllByType('Pressable').length,0,'RN pressables must not cross the native sheet touch boundary');assert.equal(sheet.findAllByType('View').length,0);const choices=sheet.findAllByType('SheetButton');assert.equal(choices.length,3);await act(async()=>choices[1].props.onPress());assert.equal(r.root.findAllByType('BottomSheet').length,0);assert(texts(r).includes('Hampir!'));assert.equal(r.root.findByProps({testID:'pet-room'}).props.style.height,initialHeight);await act(async()=>press(r,'Lanjut').props.onPress());assert.equal(r.root.findByType('BottomSheet').findAllByType('SheetButton').length,3);}finally{await act(async()=>r.unmount())}});

test('daily quiz resumes saved answers and reopening completion cannot play for a second reward',async()=>{
 let r;await act(async()=>{r=Renderer.create(screen('pet'))});try{
 await act(async()=>press(r,'Main kuis').props.onPress());await act(async()=>r.root.findByType('BottomSheet').findAllByType('SheetButton')[0].props.onPress());
 await act(async()=>press(r,'Tutup kuis').props.onPress());await act(async()=>press(r,'Main kuis').props.onPress());assert.equal(storedQuiz.answers.length,1);assert(texts(r).includes('Memindahkan alokasi'));
 for(let i=1;i<5;i++){await act(async()=>r.root.findByType('BottomSheet').findAllByType('SheetButton')[0].props.onPress());await act(async()=>press(r,'Lanjut').props.onPress());}
 assert.equal(storedQuiz.reward,5);await act(async()=>press(r,'Selesai bermain').props.onPress());await act(async()=>press(r,'Kuis selesai').props.onPress());assert.equal(r.root.findAllByType('BottomSheet').length,0);assert.equal(storedQuiz.answers.length,5);assert.equal(storedQuiz.reward,5);
 }finally{await act(async()=>r.unmount())}
});
test('calendar-only history selects records and the month picker navigates years',async()=>{
 const {TransactionHistory}=load('../src/components/transaction-history.tsx');let r;const entries=[{id:'a',title:'Roti Senin',kind:'expense',amount:10000,occurred_on:'2026-10-05'},{id:'b',title:'Uang saku',kind:'income',amount:100000,occurred_on:'2026-10-06'}];
 await act(async()=>{r=Renderer.create(React.createElement(TransactionHistory,{transactions:entries,today:'2026-10-06',renderEntry:t=>React.createElement('Text',{key:t.id},t.title)}))});try{
 assert(texts(r).includes('Uang saku'));assert(!texts(r).includes('Roti Senin'));await act(async()=>r.root.findByProps({testID:'calendar-2026-10-05'}).props.onPress());assert(texts(r).includes('Roti Senin'));assert(!texts(r).includes('Uang saku'));assert(r.root.findByProps({testID:'calendar-2026-10-07'}).props.disabled);
 assert.equal(press(r,'Daftar bulan'),undefined);assert.equal(press(r,'Kalender'),undefined);await act(async()=>press(r,'Pilih bulan catatan').props.onPress());const sheet=r.root.findByType('BottomSheet');assert.equal(sheet.findAllByType('Pressable').length,0);assert.equal(sheet.props.contentColor,'#123D43');assert.equal(r.root.findByProps({testID:'next-year'}).props.disabled,true);await act(async()=>r.root.findByProps({testID:'previous-year'}).props.onPress());assert(texts(r).includes('2025'));await act(async()=>r.root.findByProps({testID:'next-year'}).props.onPress());const button=r.root.findByProps({testID:'month-9'});assert.equal(button.findByType('SheetText').props.textStyle.fontFamily,'JakartaBold');assert.equal(button.findByType('SheetText').props.numberOfLines,1);await act(async()=>button.props.onPress());assert(texts(r).includes('September 2026'));assert(!texts(r).includes('Roti Senin'));assert.equal(r.root.findAllByType('BottomSheet').length,0);
 }finally{await act(async()=>r.unmount())}
});
