import { useState } from 'react';
import { requestPetWidget } from '../hooks/usePetWidget';
import { Text, View, Switch, Platform } from 'react-native';
import { Card, Button, type, styles, colors } from './ui';
import { learnedReminderHour } from '../lib/reminder-plan.ts';
import type { usePetReminders } from '../hooks/usePetReminders';
export function ReminderSettings({ name, reminders }: { name: string; reminders: ReturnType<typeof usePetReminders> }) {
  const { state, error } = reminders;
  const [busy, setBusy] = useState(false), [widgetNote, setWidgetNote] = useState('');
  async function toggle(v: boolean) { setBusy(true); try { await reminders.toggle(v); } finally { setBusy(false); } }
  function pin() { try { setWidgetNote(requestPetWidget() ? 'Konfirmasi penempatan widget di layar utama.' : 'Launcher ini tidak mendukung tombol tambah. Gunakan langkah di bawah.'); } catch { setWidgetNote('Pasang widget melalui menu layar utama di bawah.'); } }
  const hour = state.automatic ? learnedReminderHour(state.activity, state.lastOpened, state.hour) : state.hour;
  return <Card><Text style={type.heading}>Sapaan dari {name}</Text><Text style={type.body}>Pengingat lembut setelah 1, 3, 7, 14 dan 30 hari tanpa membuka aplikasi. Membuka aplikasi menghentikan sapaan hari itu. Tidak ada pengurangan level.</Text><View style={[styles.row, { justifyContent: 'space-between' }]}><Text style={type.body}>Izinkan pengingat di ponsel ini</Text><Switch accessibilityLabel="Izinkan pengingat teman macan" value={state.enabled} disabled={busy} onValueChange={v => void toggle(v)} trackColor={{ true: colors.accent }} /></View>{state.enabled && <><View style={[styles.row, { justifyContent: 'space-between' }]}><Text style={type.body}>Belajar jam dari kebiasaanku</Text><Switch accessibilityLabel="Jam pengingat otomatis" value={state.automatic} onValueChange={reminders.setAutomatic} trackColor={{ true: colors.accent }} /></View><Text style={type.body}>Jam sapaan {String(hour).padStart(2,'0')}:00, waktu ponsel. {state.automatic ? 'Mulai 20:00; menyesuaikan setelah setidaknya 5 hari scan atau simpan catatan. Tidak dikirim dini hari.' : 'Jam pilihanmu.'}</Text>{!state.automatic && <View style={{ gap: 8 }}>{[8,12,18,20,21].map(h => <Button key={h} secondary text={`${String(h).padStart(2,'0')}:00${h === state.hour ? ' dipilih' : ''}`} onPress={() => reminders.setHour(h)} />)}</View>}</>}{error && <Text accessibilityRole="alert" style={type.body}>{error}</Text>}<Text style={[type.body,{fontSize:11}]}>Waktu aktivitas dipelajari di perangkat ini. Tidak ada angka keuangan di notifikasi.</Text>{Platform.OS === 'android' && <><Button secondary text="Tambahkan widget ke layar utama" onPress={pin} />{widgetNote && <Text accessibilityRole="alert" style={type.body}>{widgetNote}</Text>}<Text style={type.body}>Tahan area kosong di layar utama ponsel, pilih Widget, cari MauCuan, lalu tarik Teman Macan ke layar. Ketuk widget untuk membuka check-in atau kamar.</Text></>}</Card>;
}
