import { useState, type ReactNode } from 'react';
import { Pressable, Text, View, useWindowDimensions } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Host, BottomSheet, Column, Row, Button as NativeButton, Text as NativeText } from '@expo/ui';
import { monthDays, monthLabel, dayStatus } from '../lib/calendar';
import { money, readableDay, type Transaction } from '../lib/finance';
import { Card, colors, type, styles } from './ui';
const months = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
export function TransactionHistory({ transactions, today, renderEntry }: { transactions: Transaction[]; today: string; renderEntry: (t: Transaction) => ReactNode }) {
  const [month, setMonth] = useState(today.slice(0, 7)), [selected, setSelected] = useState(today);
  const [mode, setMode] = useState<'calendar' | 'list'>('calendar'), [filter, setFilter] = useState('all');
  const [picker, setPicker] = useState(false), [year, setYear] = useState(Number(month.slice(0, 4)));
  const width = Math.min(useWindowDimensions().width - 48, 500);
  const entries = transactions.filter(t => t.occurred_on.startsWith(month));
  const filtered = entries.filter(t => filter === 'all' || t.kind === filter);
  const { offset, days } = monthDays(month);
  const visibleDays = [...new Set(filtered.map(t => t.occurred_on))].sort().reverse();
  const chosen = filtered.filter(t => t.occurred_on === selected);
  return <>
    <View style={[styles.row, { justifyContent: 'space-between' }]}>
      <Pressable accessibilityRole="button" accessibilityLabel="Pilih bulan catatan" onPress={() => { setYear(Number(month.slice(0, 4))); setPicker(true); }} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 8 }}><Text style={type.heading}>{monthLabel(month)}</Text><Ionicons name="chevron-down" size={16} color={colors.accent} /></Pressable>
    </View>
    <View style={[styles.row, { backgroundColor: colors.white, padding: 4, borderRadius: 18 }]}>{([['calendar', 'Kalender'], ['list', 'Daftar bulan']] as const).map(([value, label]) => <Pressable key={value} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected: mode === value }} onPress={() => setMode(value)} style={{ flex: 1, minHeight: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: mode === value ? colors.mist : colors.white }}><Text style={type.heading}>{label}</Text></Pressable>)}</View>
    <Card><Text style={type.body}>{entries.length} catatan di bulan ini</Text><View style={[styles.row, { justifyContent: 'space-between' }]}><View><Text style={type.body}>Masuk</Text><Text style={type.heading}>{money(entries.filter(t => t.kind === 'income').reduce((n, t) => n + Number(t.amount), 0))}</Text></View><View><Text style={type.body}>Keluar</Text><Text style={type.heading}>{money(entries.filter(t => t.kind === 'expense').reduce((n, t) => n + Number(t.amount), 0))}</Text></View></View></Card>
    {mode === 'calendar' && <Card><View style={{ flexDirection: 'row' }}>{['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab', 'Min'].map(label => <Text key={label} style={[type.body, { width: '14.2857%', textAlign: 'center', fontSize: 11 }]}>{label}</Text>)}</View><View style={{ flexDirection: 'row', flexWrap: 'wrap' }}>{Array.from({ length: offset }, (_, i) => <View key={`gap-${i}`} style={{ width: '14.2857%', height: 48 }} />)}{days.map(day => {
      const state = dayStatus(day, today, entries), disabled = day > today;
      const bg = state === 'today' ? colors.accent : state === 'recorded' ? colors.orange : state === 'empty' ? '#EDF0F1' : colors.white;
      return <Pressable key={day} testID={`calendar-${day}`} accessibilityRole="button" accessibilityLabel={`${readableDay(day)}, ${entries.filter(t => t.occurred_on === day).length} catatan`} accessibilityState={{ selected: day === selected, disabled }} disabled={disabled} onPress={() => setSelected(day)} style={{ width: '14.2857%', height: 48, alignItems: 'center', justifyContent: 'center' }}><View style={{ width: 34, height: 36, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: bg, borderColor: day === selected ? colors.ink : 'transparent', borderWidth: 2 }}><Text style={[type.heading, { fontSize: 12, color: state === 'today' || state === 'recorded' ? colors.white : disabled ? colors.muted : colors.ink }]}>{Number(day.slice(-2))}</Text></View></Pressable>;
    })}</View><Text style={[type.body, { fontSize: 11 }]}>Jingga: ada catatan. Biru: hari ini. Abu-abu: belum ada catatan.</Text></Card>}
    <View style={[styles.row, { flexWrap: 'wrap' }]}>{[['all', 'Semua'], ['expense', 'Pengeluaran'], ['income', 'Pemasukan']].map(([value, label]) => <Pressable key={value} accessibilityRole="button" accessibilityState={{ selected: filter === value }} onPress={() => setFilter(value)} style={{ minHeight: 44, justifyContent: 'center', paddingHorizontal: 12, borderRadius: 18, backgroundColor: filter === value ? colors.mist : colors.white }}><Text style={type.body}>{label}</Text></Pressable>)}</View>
    {mode === 'calendar' ? <Card><Text style={type.heading}>{readableDay(selected)}</Text>{chosen.length ? chosen.map(renderEntry) : <Text style={type.body}>Belum ada {filter === 'all' ? 'catatan' : filter === 'income' ? 'pemasukan' : 'pengeluaran'} di tanggal ini.</Text>}</Card> : visibleDays.length ? visibleDays.map(day => <Card key={day}><Text style={type.heading}>{readableDay(day)}</Text>{filtered.filter(t => t.occurred_on === day).map(renderEntry)}</Card>) : <Card><Text style={type.body}>Belum ada catatan yang sesuai di bulan ini.</Text></Card>}
    <Host style={{ height: 0 }} colorScheme="light" seedColor={colors.accent}><BottomSheet isPresented={picker} onDismiss={() => setPicker(false)} contentPadding={24} containerColor="#FFF4E7"><Column spacing={12} style={{ width }}><Row spacing={8}><NativeButton variant="outlined" onPress={() => setYear(n => Math.max(1900, n - 1))}><NativeText>Tahun sebelumnya</NativeText></NativeButton><NativeButton variant="outlined" onPress={() => setYear(n => Math.min(Number(today.slice(0, 4)), n + 1))}><NativeText>Tahun berikutnya</NativeText></NativeButton></Row><NativeText textStyle={{ fontSize: 20, color: colors.ink }}>{String(year)}</NativeText>{[0, 3, 6, 9].map(start => <Row key={start} spacing={8}>{months.slice(start, start + 3).map((label, j) => <NativeButton key={label} variant="outlined" disabled={`${year}-${String(start + j + 1).padStart(2, '0')}` > today.slice(0, 7)} style={{ width: (width - 16) / 3 }} onPress={() => { const next = `${year}-${String(start + j + 1).padStart(2, '0')}`; if (next > today.slice(0, 7)) return; setMonth(next); setSelected(next === today.slice(0, 7) ? today : next + '-01'); setPicker(false); }}><NativeText textStyle={{ fontSize: 12, color: `${year}-${String(start + j + 1).padStart(2, '0')}` > today.slice(0, 7) ? colors.muted : colors.ink }}>{label}</NativeText></NativeButton>)}</Row>)}</Column></BottomSheet></Host>
  </>;
}

